//! Runtime support for `#[web_component]`. This crate is generic —
//! it doesn't know about any specific component. Each component gets
//! its mount/update/unmount trio generated by the macro; this crate
//! just implements what those trios call into: tracking one Leptos
//! reactive scope per DOM host element, so disconnectedCallback can
//! dispose it cleanly (no leaked reactivity across remounts, per the
//! contract in CONTRACT.md).

use leptos::*;
use std::cell::RefCell;
use std::collections::HashMap;
use wasm_bindgen::{JsCast, JsValue};
use web_sys::HtmlElement;

// wasm is single-threaded, so thread_local + RefCell (not Mutex/Lazy,
// which need Send + Sync) is the right tool here — Send/Sync don't
// apply on the wasm32 target this crate actually ships to.
thread_local! {
    /// One disposer per mounted host element, keyed by a stable id we
    /// stash on the element itself (via a data attribute) since
    /// `HtmlElement` isn't `Hash`.
    static SCOPES: RefCell<HashMap<String, Box<dyn FnOnce()>>> = RefCell::new(HashMap::new());
    static NEXT_ID: RefCell<u64> = RefCell::new(0);
}

fn host_id(host: &HtmlElement) -> String {
    if let Some(existing) = host.get_attribute("data-wc-id") {
        return existing;
    }
    let id = NEXT_ID.with(|n| {
        let mut n = n.borrow_mut();
        *n += 1;
        format!("wc-{}", *n)
    });
    host.set_attribute("data-wc-id", &id).ok();
    id
}

/// Called from the macro-generated `__mount_*` function.
pub fn mount<F, V>(host: HtmlElement, view_fn: F)
where
    F: FnOnce() -> V + 'static,
    V: IntoView,
{
    let id = host_id(&host);
    let node: web_sys::Node = host.clone().into();
    let disposer = leptos::mount_to(node.unchecked_into(), view_fn);
    SCOPES.with(|scopes| {
        scopes
            .borrow_mut()
            .insert(id, Box::new(move || { let _ = disposer; }));
    });
}

/// Called from the macro-generated `__update_*` function when an
/// observed attribute changes after initial mount. Default behavior:
/// re-mount is left to the component's own signals via a follow-up
/// call; for most components you'll instead expose a setter signal.
/// This hook exists so more advanced components can react without a
/// full remount — kept intentionally simple in v0.1.
pub fn update(_host: HtmlElement, _props_json: JsValue) {
    // v0.1: attributes are read once at mount. Live-updating props
    // after mount is the main thing to design next (see README "Next
    // steps") — likely via a shared `RwSignal` stored alongside the
    // disposer in `SCOPES` that `update` writes into.
}

/// Called from the macro-generated `__unmount_*` function
/// (disconnectedCallback). Disposes the reactive scope so signals /
/// effects for this instance stop running — required by the contract
/// so remounting the same tag doesn't leak reactivity.
pub fn unmount(host: HtmlElement) {
    let id = host_id(&host);
    let dispose = SCOPES.with(|scopes| scopes.borrow_mut().remove(&id));
    if let Some(dispose) = dispose {
        dispose();
    }
}

/// Parses a single named field out of the JSON object passed from JS
/// (`{"label": "React", "initial": "4"}` — attribute values arrive as
/// strings, so numeric/bool types go through `FromStr` after a plain
/// string extraction).
pub fn parse_prop<T: PropParse>(props_json: &JsValue, name: &str) -> T {
    let s = props_json.as_string().unwrap_or_default();
    let map: serde_json::Value = serde_json::from_str(&s).unwrap_or(serde_json::Value::Null);
    let raw = map.get(name).and_then(|v| v.as_str()).unwrap_or_default();
    T::parse(raw)
}

/// Small conversion trait so `parse_prop::<i32>` / `::<String>` /
/// `::<bool>` all just work from the string attribute value.
pub trait PropParse {
    fn parse(raw: &str) -> Self;
}

impl PropParse for String {
    fn parse(raw: &str) -> Self {
        raw.to_string()
    }
}
impl PropParse for i32 {
    fn parse(raw: &str) -> Self {
        raw.parse().unwrap_or_default()
    }
}
impl PropParse for f64 {
    fn parse(raw: &str) -> Self {
        raw.parse().unwrap_or_default()
    }
}
impl PropParse for bool {
    fn parse(raw: &str) -> Self {
        raw == "true"
    }
}

pub use leptos_webcomponent_macro::web_component;
