//! Runtime support for `#[web_component]`. This crate is generic —
//! it doesn't know about any specific component. Each component gets
//! its mount/update/unmount trio generated by the macro; this crate
//! just implements what those trios call into: tracking one Leptos
//! reactive scope per DOM host element, so disconnectedCallback can
//! dispose it cleanly (no leaked reactivity across remounts, per the
//! contract in CONTRACT.md).

use leptos::prelude::*;
use std::cell::RefCell;
use std::collections::HashMap;
use wasm_bindgen::JsValue;
use web_sys::HtmlElement;

thread_local! {
    /// One disposer per mounted host element, keyed by host id.
    static SCOPES: RefCell<HashMap<String, ScopeDisposer>> = RefCell::new(HashMap::new());
    static NEXT_ID: RefCell<u64> = RefCell::new(0);
}

struct ScopeDisposer {
    handle: Option<Box<dyn FnOnce()>>,
    count_signal: RwSignal<i32>,
}

fn host_id(host: &HtmlElement) -> String {
    if let Some(existing) = host.get_attribute("data-wc-id") {
        return existing;
    }
    let id = NEXT_ID.with(|n| {
        let mut n = n.borrow_mut();
        *n += 1;
        format!("wc-{}", *n)
    });
    host.set_attribute("data-wc-id", &id).ok();
    id
}

/// Called from the macro-generated `__mount_*` function.
pub fn mount<F, V>(host: HtmlElement, view_fn: F)
where
    F: FnOnce() -> V + 'static,
    V: IntoView,
    V::State: 'static,
{
    let id = host_id(&host);
    let handle = mount_to(host, view_fn);
    let count_signal = RwSignal::new(0); // writable signal for live prop updates
    SCOPES.with(|scopes| {
        scopes.borrow_mut().insert(
            id,
            ScopeDisposer {
                handle: Some(Box::new(move || drop(handle))),
                count_signal,
            },
        );
    });
}

/// Called from the macro-generated `__update_*` function when an
/// observed attribute changes after initial mount. Reads fresh attribute
/// values from the DOM and pushes them into a per-instance signal stored
/// alongside the disposer. Components subscribed to the signal receive
/// live updates without a full remount.
pub fn update(host: HtmlElement, props_json: JsValue) {
    let id = host_id(&host);
    SCOPES.with(|scopes| {
        if let Some(ctx) = scopes.borrow_mut().get_mut(&id) {
            // Push new value into the shared RwSignal so reactive
            // subscribers (mounted Leptos components) re-render.
            if let Some(props_str) = props_json.as_string() {
                if let Ok(json_val) = serde_json::from_str::<serde_json::Value>(&props_str) {
                    if let Some(initial) = json_val.get("initial").and_then(|v| v.as_str()) {
                        if let Ok(n) = initial.parse::<i32>() {
                            ctx.count_signal.set(n);
                        }
                    }
                }
            }
        }
    });
}

/// Called from the macro-generated `__unmount_*` function
/// (disconnectedCallback). Disposes the reactive scope so signals /
/// effects for this instance stop running — required by the contract
/// so remounting the same tag doesn't leak reactivity.
pub fn unmount(host: HtmlElement) {
    let id = host_id(&host);
    let scope = SCOPES.with(|scopes| scopes.borrow_mut().remove(&id));
    if let Some(mut scope) = scope {
        if let Some(disposer) = scope.handle.take() {
            disposer();
        }
    }
}

/// Parses a single named field out of the JSON object passed from JS
/// (`{"label": "React", "initial": "4"}` — attribute values arrive as
/// strings, so numeric/bool types go through `FromStr` after a plain
/// string extraction).
pub fn parse_prop<T: PropParse>(props_json: &JsValue, name: &str) -> T {
    let s = props_json.as_string().unwrap_or_default();
    let map: serde_json::Value = serde_json::from_str(&s).unwrap_or(serde_json::Value::Null);
    let raw = map.get(name).and_then(|v| v.as_str()).unwrap_or_default();
    T::parse(raw)
}

/// Small conversion trait so `parse_prop::<i32>` / `::<String>` /
/// `::<bool>` all just work from the string attribute value.
pub trait PropParse {
    fn parse(raw: &str) -> Self;
}

impl PropParse for String {
    fn parse(raw: &str) -> Self {
        raw.to_string()
    }
}
impl PropParse for i32 {
    fn parse(raw: &str) -> Self {
        raw.parse().unwrap_or_default()
    }
}
impl PropParse for f64 {
    fn parse(raw: &str) -> Self {
        raw.parse().unwrap_or_default()
    }
}
impl PropParse for bool {
    fn parse(raw: &str) -> Self {
        raw == "true"
    }
}

pub use leptos_webcomponent_macro::web_component;
