// scripts/generate-types.mjs
//
// Generates TypeScript declarations for Leptos web components straight
// from their __meta_* descriptors — single source of truth, no hand-
// written .d.ts per widget.
//
// Usage:
//   node scripts/generate-types.mjs <glue-dir> [-o out.d.ts]
//
// <glue-dir> is a directory containing the wasm-bindgen `--target web`
// output: <name>.js + <name>_bg.wasm (e.g. examples/lx-counter/www).
// Node loads the glue directly (the .wasm bytes are passed to init), so
// no browser or bundler is involved.
//
// The emitted file augments JSX.IntrinsicElements so host frameworks
// get tag/attribute autocomplete and event-name typing:
//
//   <lx-counter label="Hi" count="3" />

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, resolve, basename } from "node:path";
import { pathToFileURL } from "node:url";

function parseArgs(argv) {
  const args = { out: null, dir: null };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "-o") args.out = argv[++i];
    else args.dir = argv[i];
  }
  if (!args.dir) {
    console.error("usage: node generate-types.mjs <glue-dir> [-o out.d.ts]");
    process.exit(2);
  }
  return args;
}

async function loadGlue(dir) {
  const files = readdirSync(dir);
  const js = files.find((f) => f.endsWith(".js") && !f.endsWith("_bg.wasm.d.ts"));
  const wasm = files.find((f) => f.endsWith("_bg.wasm"));
  if (!js || !wasm) {
    console.error(`no wasm-bindgen glue found in ${dir}`);
    process.exit(2);
  }
  const mod = await import(pathToFileURL(join(resolve(dir), js)).href);
  // initSync takes raw bytes — no fetch involved, works identically in
  // Node and browsers.
  const bytes = new Uint8Array(readFileSync(join(resolve(dir), wasm)));
  mod.initSync(bytes);
  return mod;
}

function metas(mod) {
  const out = [];
  for (const name of Object.keys(mod)) {
    if (!name.startsWith("__meta_")) continue;
    try {
      out.push(JSON.parse(mod[name]()));
    } catch (err) {
      console.warn(`skipping ${name}: ${err?.message ?? err}`);
    }
  }
  return out;
}

const camel = (s) =>
  s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase()).replace(/^./, (c) => c.toUpperCase());
const safeId = (tag) => tag.replace(/[^a-zA-Z0-9]/g, "_");

function renderComponent(meta) {
  const lines = [
    ...(meta.attrs || []).map((a) => `  ${JSON.stringify(a)}?: string;`),
    '  /** Slot drop point rendered inside the component (CONTRACT.md §7). */',
    '  "data-wc-slot"?: string;',
    ...(meta.events || []).map(
      (e) =>
        `  ${JSON.stringify(`on${camel(e)}`)}?: (event: CustomEvent<WcEventDetail>) => void;`
    ),
  ].filter((l) => !l.startsWith("  ;"));

  return `/** ${meta.tag} — Leptos web component (source of truth: __meta descriptor). */
export interface Wc${safeId(meta.tag)}Props extends WcBaseAttrs {
${lines.join("\n")}
}
`;
}

function renderIntrinsics(metas) {
  const entries = metas
    .map((m) => `      ${JSON.stringify(m.tag)}: Wc${safeId(m.tag)}Props;`)
    .join("\n");
  return `declare global {
  namespace JSX {
    interface IntrinsicElements {
${entries}
    }
  }
}
`;
}

const HEADER = `// Generated by wc-bridge scripts/generate-types.mjs — do not edit.
// Attribute values are always strings at the DOM level (CONTRACT.md §1);
// event details are plain JSON objects (CONTRACT.md §2).

type WcEventDetail = Record<string, unknown>;

interface WcBaseAttrs {
  class?: string;
  style?: string;
  id?: string;
  slot?: string;
  "data-wc-strict"?: boolean;
}

`;

const FOOTER = `export {};
`;

async function main() {
  const { dir, out } = parseArgs(process.argv.slice(2));
  const mod = await loadGlue(dir);
  const metasList = metas(mod);
  if (!metasList.length) {
    console.error("no __meta_* exports found in glue module");
    process.exit(1);
  }

  let code = HEADER;
  for (const m of metasList) code += renderComponent(m) + "\n";
  code += "\n" + renderIntrinsics(metasList) + FOOTER;

  const outFile =
    out || join(dir, `${basename(metasList[0].tag)}-widgets.d.ts`).replace(`${basename(metasList[0].tag)}`, "lx-widgets");
  writeFileSync(outFile, code);
  console.log(
    `generated ${outFile} for ${metasList.map((m) => m.tag).join(", ")}`
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
