// Generated by wc-bridge scripts/generate-types.mjs — do not edit.
// Attribute values are always strings at the DOM level (CONTRACT.md §1);
// event details are plain JSON objects (CONTRACT.md §2).

type WcEventDetail = Record<string, unknown>;

interface WcBaseAttrs {
  class?: string;
  style?: string;
  id?: string;
  slot?: string;
  "data-wc-strict"?: boolean;
}

/** lx-counter — Leptos web component (source of truth: __meta descriptor). */
export interface Wclx_counterProps extends WcBaseAttrs {
  "count"?: string;
  "label"?: string;
  "tags"?: string;
  /** Slot drop point rendered inside the component (CONTRACT.md §7). */
  "data-wc-slot"?: string;
  "onCountChanged"?: (event: CustomEvent<WcEventDetail>) => void;
}


declare global {
  namespace JSX {
    interface IntrinsicElements {
      "lx-counter": Wclx_counterProps;
    }
  }
}
export {};
